version: '3.8'

services:
  web:
    build: .
    command: gunicorn -k eventlet -w 4 --timeout 120 -b 0.0.0.0:5000 run:app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=${SECRET_KEY}
      - API_KEY=${API_KEY}
